# nodeLinker: node-modules

packageExtensions:
    next@13.1.6:
        dependencies:
            react: 18.2.0
            react-dom: 18.2.0
            '@next/font': 13.1.6
    '@next/font@13.1.6':
        dependencies:
            next: 13.1.6

# '@next/font@^13':
#     dependencies:
#         next: '^13'
#         react: '^18'
#         react-dom: '^18'
#     peerDependencies:
#         next: '^13'
# next@^13:
#     dependencies:
#         '@next/font': '^13'

# 'vite-plugin-dts@*':
#     dependencies:
#         react: '^18'
#         '@types/react': '^18'
#         react-dom: '^18'
#         '@types/react-dom': '^18'

# '@storybook/addon-docs@*':
#     dependencies:
#         '@babel/core': '*'
#         'webpack': '^5'
# '@storybook/builder-vite@*':
#     dependencies:
#         'react': '*'
#         'react-dom': '*'
# '@devtools-ds/themes@*':
#     dependencies:
#         'react-dom': '*'

# '@mdx-js/react@*':
#     dependencies:
#         react: '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
