# nodeLinker: node-modules

packageExtensions:
    next@13.1.6:
        dependencies:
            react: 18.2.0
            react-dom: 18.2.0
            '@next/font': 13.1.6
    '@next/font@13.1.6':
        dependencies:
            next: 13.1.6

    '@toast-ui/editor@*':
        dependencies:
            prosemirror-transform: '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
