# nodeLinker: node-modules

packageExtensions:
    '@next/font@^13':
        dependencies:
            next: '^13'
            react: '^18'
            react-dom: '^18'

    'vite-plugin-dts@*':
        dependencies:
            react: '^18'
            '@types/react': '^18'
            react-dom: '^18'
            '@types/react-dom': '^18'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
